// <auto-generated />
using System;
using HiClass.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiClass.Persistence.Migrations
{
    [DbContext(typeof(SharedLessonDbContext))]
    [Migration("20240328200336_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<short?>("Rating")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ReasonForNotConducting")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserRecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasTheJointLesson")
                        .HasColumnType("boolean");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ClassReceiverId");

                    b.HasIndex("ClassSenderId");

                    b.HasIndex("FeedbackId")
                        .IsUnique();

                    b.HasIndex("InvitationId");

                    b.HasIndex("UserRecipientId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateOfInvitation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid");

                    b.HasKey("InvitationId");

                    b.HasIndex("ClassReceiverId");

                    b.HasIndex("ClassSenderId");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("UserReceiverId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Discipline", b =>
                {
                    b.Property<Guid>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("DisciplineId");

                    b.HasIndex("DisciplineId")
                        .IsUnique();

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DisciplineId = new Guid("10cf60af-5335-4bc2-af52-aefe65a5be55"),
                            Title = "Russian language"
                        },
                        new
                        {
                            DisciplineId = new Guid("cf24ccee-ecfc-4604-9e77-757e0be8c27e"),
                            Title = "Russian literature"
                        },
                        new
                        {
                            DisciplineId = new Guid("658673ae-fa20-4aff-a73b-4d30dd45e976"),
                            Title = "English as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("7706190e-9a1d-414d-93ed-5e893b91cc01"),
                            Title = "German as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("be984298-c6f4-473f-b984-9ee61efa8ee2"),
                            Title = "French as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("3c6f6b7f-f47c-4523-a6f9-24869336b088"),
                            Title = "Italian as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("34ebee0e-a3f2-4127-b554-f60f255d3ab9"),
                            Title = "Spanish as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("4154f9b3-9eda-42cc-9f31-9f9ac7613ae8"),
                            Title = "Chinese as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("c96a70f5-275d-4b5a-9260-fd7e791dbf71"),
                            Title = "Mathematics"
                        },
                        new
                        {
                            DisciplineId = new Guid("84a93d4a-bc5e-45e7-846b-a9d7dd8fae27"),
                            Title = "Social science"
                        },
                        new
                        {
                            DisciplineId = new Guid("4f94bba2-0a3e-46f0-8a97-ed1ffecc5c81"),
                            Title = "Physics"
                        },
                        new
                        {
                            DisciplineId = new Guid("3b879215-b498-4b58-becc-6b4458cba53c"),
                            Title = "Astronomy"
                        },
                        new
                        {
                            DisciplineId = new Guid("9efc3cff-455a-418c-a28a-d50614ef104e"),
                            Title = "Chemistry"
                        },
                        new
                        {
                            DisciplineId = new Guid("aa62d79a-c78a-41da-a9bb-15b90b220f96"),
                            Title = "Biology"
                        },
                        new
                        {
                            DisciplineId = new Guid("f97a1da5-4851-4b34-a1bf-ddb39c605fa9"),
                            Title = "Geography"
                        },
                        new
                        {
                            DisciplineId = new Guid("799723fb-6f76-49d8-8b9a-1c5499148bf0"),
                            Title = "History"
                        },
                        new
                        {
                            DisciplineId = new Guid("c993c589-9424-470c-8704-5bfa990740a5"),
                            Title = "Computer science"
                        },
                        new
                        {
                            DisciplineId = new Guid("df7216b0-7ecb-47ce-b85b-ddb186330754"),
                            Title = "Technology"
                        },
                        new
                        {
                            DisciplineId = new Guid("62b76391-1647-4088-b8dc-fc5f710f6afc"),
                            Title = "World art"
                        },
                        new
                        {
                            DisciplineId = new Guid("ab9e0229-48c8-49d2-999a-7af0bb37d43a"),
                            Title = "Fine arts"
                        },
                        new
                        {
                            DisciplineId = new Guid("60206daf-7115-4dc1-89e3-7718bff2b288"),
                            Title = "Crafts"
                        },
                        new
                        {
                            DisciplineId = new Guid("8ee83471-b752-4da1-b241-de580b6af2dd"),
                            Title = "Natural science"
                        },
                        new
                        {
                            DisciplineId = new Guid("1abc9cd6-2139-440e-83c6-d67d54ac7b39"),
                            Title = "Music"
                        },
                        new
                        {
                            DisciplineId = new Guid("09557099-43ee-478d-9c5c-ab66cde28588"),
                            Title = "Economics"
                        },
                        new
                        {
                            DisciplineId = new Guid("0c88e9a3-f983-4edd-a39e-b55a79336352"),
                            Title = "Regional studies"
                        },
                        new
                        {
                            DisciplineId = new Guid("4fd55b22-f8dc-4895-8426-2963e26234d4"),
                            Title = "Project-based learning"
                        },
                        new
                        {
                            DisciplineId = new Guid("1f41a7f5-7196-4d03-a49c-48affdc07716"),
                            Title = "Cultural exchange"
                        },
                        new
                        {
                            DisciplineId = new Guid("521881d5-3ed6-4f98-92e0-e43ff9431334"),
                            Title = "Vacation education"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("GradeNumber")
                        .HasMaxLength(15)
                        .HasColumnType("integer");

                    b.HasKey("GradeId");

                    b.HasIndex("GradeId")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = new Guid("caacefd8-fc3c-498c-948b-1ee64a6705c7"),
                            GradeNumber = 1
                        },
                        new
                        {
                            GradeId = new Guid("0f5887db-a186-4d38-ab5c-451ba3df9f87"),
                            GradeNumber = 2
                        },
                        new
                        {
                            GradeId = new Guid("22876a40-ea33-41ca-b027-f6e84f8e089a"),
                            GradeNumber = 3
                        },
                        new
                        {
                            GradeId = new Guid("179d2b0c-fe47-43d6-a2bb-0dbfa7dd4b7c"),
                            GradeNumber = 4
                        },
                        new
                        {
                            GradeId = new Guid("52cdfa78-5ffe-4efd-9be0-65c33441c344"),
                            GradeNumber = 5
                        },
                        new
                        {
                            GradeId = new Guid("e5f7a7be-9cd8-40fd-8e89-7ca24267590d"),
                            GradeNumber = 6
                        },
                        new
                        {
                            GradeId = new Guid("fa9b3948-5db2-4030-b550-b9f6526db511"),
                            GradeNumber = 7
                        },
                        new
                        {
                            GradeId = new Guid("3e060df3-e993-4360-81ec-526bfd4300de"),
                            GradeNumber = 8
                        },
                        new
                        {
                            GradeId = new Guid("43fc7b25-7e5b-40fb-9ae8-2daf02cb1c65"),
                            GradeNumber = 9
                        },
                        new
                        {
                            GradeId = new Guid("edefb369-d929-4ce3-9867-f759fe65fa5d"),
                            GradeNumber = 10
                        },
                        new
                        {
                            GradeId = new Guid("d6196793-8541-4568-b9b5-ed79db4663d6"),
                            GradeNumber = 11
                        },
                        new
                        {
                            GradeId = new Guid("54e5c3fe-e1b7-479c-b122-317668d84867"),
                            GradeNumber = 12
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("LanguageId");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("e4236f9a-4bc8-4865-b162-90d2540f999b"),
                            Title = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("5ce9f24b-c4b5-42eb-aa93-aaedc79bb25d"),
                            Title = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("2bd7c6c4-fd62-4e43-a7c1-0cca723f22f8"),
                            Title = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("74f2bfcc-8fc4-44a0-b635-3096bbd29ac2"),
                            Title = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("409fae6a-0e64-456f-aa82-59ad3860d1e0"),
                            Title = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("db9b3b01-575d-4ac0-a3bf-f3c98f240c5c"),
                            Title = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("08ffc2de-fd41-4746-8f44-2b1094cbeb7b"),
                            Title = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("d112b085-f98d-4e6e-b0e9-17d0bf8ba8bd"),
                            Title = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("321970b9-9162-4354-86f0-eea273eaac92"),
                            Title = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("7c9cdd67-ab97-4b82-97ed-fc1cc859e40d"),
                            Title = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("36bb06f4-9dc3-4824-8e80-d9685528d96e"),
                            Title = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("7dbceb90-9f52-40e5-afff-086b069fba3b"),
                            Title = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("9d4cc8b9-6669-4e89-a989-fd6f2f91e9c3"),
                            Title = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("4d88746d-9115-43c1-8e56-b0c37de89e97"),
                            Title = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("4bac2286-3621-4aa0-b240-fc92bb52cd8c"),
                            Title = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("39374a1f-207f-4f52-b84e-f054da08888d"),
                            Title = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("ea5615bf-b846-4b0e-aa46-3ba2fd817e08"),
                            Title = "Uzbek"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("CityId");

                    b.HasIndex("InstitutionId")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.InstitutionType", b =>
                {
                    b.Property<Guid>("InstitutionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("InstitutionTypeId");

                    b.HasIndex("InstitutionTypeId")
                        .IsUnique();

                    b.ToTable("InstitutionTypes");

                    b.HasData(
                        new
                        {
                            InstitutionTypeId = new Guid("4f887a70-b6d3-4a94-a30b-b51bf5d750f3"),
                            Title = "School"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("efe4663e-cda4-42c9-aca5-7c047a050282"),
                            Title = "Gymnasium"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("e57afc06-6698-40e2-ac4f-599ebba14c2e"),
                            Title = "Lyceum"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("ff70890b-797b-431c-a019-fb3586da5036"),
                            Title = "College"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("CityId");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassId")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("0445c42a-4062-4040-b8e0-2f9f0b01bd4d"),
                            Title = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("f771c782-23b8-4ac7-9ee4-2b88475c6761"),
                            Title = "User"
                        },
                        new
                        {
                            RoleId = new Guid("b3f26093-1a1f-4ff6-b610-37cc46e36ea2"),
                            Title = "Manager"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsATeacher")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAnExpert")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCreatedAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInstitutionVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("LastOnlineAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassDiscipline", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ClassId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("ClassDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId", "ClassId");

                    b.HasIndex("ClassId");

                    b.HasIndex("LanguageId", "ClassId")
                        .IsUnique();

                    b.ToTable("ClassLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.InstitutionTypeInstitution", b =>
                {
                    b.Property<Guid>("InstitutionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.HasKey("InstitutionTypeId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("InstitutionTypeId", "InstitutionId")
                        .IsUnique();

                    b.ToTable("InstitutionTypesInstitutions");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserDiscipline", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("UserDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserGrade", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GradeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId", "GradeId")
                        .IsUnique();

                    b.ToTable("UserGrades");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserLanguage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Feedback", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassReceiver")
                        .WithMany("ReceivedFeedBacks")
                        .HasForeignKey("ClassReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassSender")
                        .WithMany("SentFeedBacks")
                        .HasForeignKey("ClassSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Communication.Invitation", "Invitation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserRecipient")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("UserRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserSender")
                        .WithMany("SentFeedbacks")
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassReceiver");

                    b.Navigation("ClassSender");

                    b.Navigation("Invitation");

                    b.Navigation("UserRecipient");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassReceiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ClassReceiverId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassSender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("ClassSenderId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserReceiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("UserReceiverId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserSender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("UserSenderId")
                        .IsRequired();

                    b.Navigation("ClassReceiver");

                    b.Navigation("ClassSender");

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.City", null)
                        .WithMany("Establishments")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("Classes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiClass.Domain.Entities.Location.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiClass.Domain.Entities.Job.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassDiscipline", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "Class")
                        .WithMany("ClassDisciplines")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Education.Discipline", "Discipline")
                        .WithMany("ClassDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassLanguage", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "Class")
                        .WithMany("ClassLanguages")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Education.Language", "Language")
                        .WithMany("ClassLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.InstitutionTypeInstitution", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Job.Institution", "Institution")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Job.InstitutionType", "InstitutionType")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("InstitutionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("InstitutionType");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserDiscipline", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Discipline", "Discipline")
                        .WithMany("UserDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserDisciplines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserGrade", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Grade", "Grade")
                        .WithMany("UserGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserGrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserLanguage", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Language", "Language")
                        .WithMany("TeacherLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserRole", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Discipline", b =>
                {
                    b.Navigation("ClassDisciplines");

                    b.Navigation("UserDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Grade", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("UserGrades");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Language", b =>
                {
                    b.Navigation("ClassLanguages");

                    b.Navigation("TeacherLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.Navigation("InstitutionTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.InstitutionType", b =>
                {
                    b.Navigation("InstitutionTypes");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.Navigation("Establishments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.Navigation("ClassDisciplines");

                    b.Navigation("ClassLanguages");

                    b.Navigation("ReceivedFeedBacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentFeedBacks");

                    b.Navigation("SentInvitations");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ReceivedFeedbacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentFeedbacks");

                    b.Navigation("SentInvitations");

                    b.Navigation("UserDisciplines");

                    b.Navigation("UserGrades");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
