// <auto-generated />
using System;
using HiClass.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiClass.Persistence.Migrations
{
    [DbContext(typeof(SharedLessonDbContext))]
    [Migration("20240519214656_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<short?>("Rating")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ReasonForNotConducting")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserRecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasTheJointLesson")
                        .HasColumnType("boolean");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ClassReceiverId");

                    b.HasIndex("ClassSenderId");

                    b.HasIndex("FeedbackId")
                        .IsUnique();

                    b.HasIndex("InvitationId");

                    b.HasIndex("UserRecipientId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateOfInvitation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid");

                    b.HasKey("InvitationId");

                    b.HasIndex("ClassReceiverId");

                    b.HasIndex("ClassSenderId");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("UserReceiverId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Discipline", b =>
                {
                    b.Property<Guid>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("DisciplineId");

                    b.HasIndex("DisciplineId")
                        .IsUnique();

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DisciplineId = new Guid("73900145-03eb-4ccd-96b0-f6efa1f47b6b"),
                            Title = "Russian language"
                        },
                        new
                        {
                            DisciplineId = new Guid("31025995-255d-4332-9741-e0e753b93b9b"),
                            Title = "Russian literature"
                        },
                        new
                        {
                            DisciplineId = new Guid("1a8f3250-fd7c-4002-88c6-ecc4fdf77b1d"),
                            Title = "English as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("9c3ed28d-40cc-4632-a20e-981783ed52ef"),
                            Title = "German as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("bf4ca7ea-e175-406a-8ac8-a4506c00d72c"),
                            Title = "French as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("6a0e52dd-f8e6-4aa9-93a8-8b41198c234d"),
                            Title = "Italian as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("a7bd920f-ee14-4654-9999-f475f6ddf9d5"),
                            Title = "Spanish as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("74b94809-08c7-49aa-9c2a-6cec777af2a1"),
                            Title = "Chinese as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("a414afd2-8cc6-4eb9-842c-35e601000f2c"),
                            Title = "Mathematics"
                        },
                        new
                        {
                            DisciplineId = new Guid("894523bb-2f9e-444f-885c-9eb8d4416515"),
                            Title = "Social science"
                        },
                        new
                        {
                            DisciplineId = new Guid("19fa1bcd-73d7-42ae-bfcc-780d393c8627"),
                            Title = "Physics"
                        },
                        new
                        {
                            DisciplineId = new Guid("a042913c-7c9d-4db9-a068-9995751cf19f"),
                            Title = "Astronomy"
                        },
                        new
                        {
                            DisciplineId = new Guid("05565abb-141d-4abe-8c14-16359ac69e82"),
                            Title = "Chemistry"
                        },
                        new
                        {
                            DisciplineId = new Guid("794f0382-0aa7-431f-9aea-4894288b5854"),
                            Title = "Biology"
                        },
                        new
                        {
                            DisciplineId = new Guid("435bb259-35d9-4207-954c-c0022c9fc5f0"),
                            Title = "Geography"
                        },
                        new
                        {
                            DisciplineId = new Guid("dbe703ad-0f2f-410e-8f7e-8b55b8ba41cf"),
                            Title = "History"
                        },
                        new
                        {
                            DisciplineId = new Guid("e6f188ef-7430-4b7b-9f82-6ee8afb2d41a"),
                            Title = "Computer science"
                        },
                        new
                        {
                            DisciplineId = new Guid("2db7c667-b8fb-446a-8d3b-42ca70d6c5fd"),
                            Title = "Technology"
                        },
                        new
                        {
                            DisciplineId = new Guid("d58a9d6d-5801-4ddd-8a6d-ec89107d5aa0"),
                            Title = "World art"
                        },
                        new
                        {
                            DisciplineId = new Guid("6c91c43b-2166-42e3-8c58-875a4408b2ab"),
                            Title = "Fine arts"
                        },
                        new
                        {
                            DisciplineId = new Guid("b1f2b5d0-d14e-4db8-9b21-d6cdf9be3f70"),
                            Title = "Crafts"
                        },
                        new
                        {
                            DisciplineId = new Guid("9f8f5380-58cf-449e-9207-9e2e485c52fd"),
                            Title = "Natural science"
                        },
                        new
                        {
                            DisciplineId = new Guid("b34e2223-1ab2-46e8-89e0-4a67d50ff351"),
                            Title = "Music"
                        },
                        new
                        {
                            DisciplineId = new Guid("bf8dee08-6dc0-4b0c-abf9-4d6e10cab222"),
                            Title = "Economics"
                        },
                        new
                        {
                            DisciplineId = new Guid("e5605d80-9f53-4a6c-9f7b-b08ec6520be8"),
                            Title = "Regional studies"
                        },
                        new
                        {
                            DisciplineId = new Guid("e11d4acd-dad9-4bb2-9d01-506e88175684"),
                            Title = "Project-based learning"
                        },
                        new
                        {
                            DisciplineId = new Guid("843e7c73-ff9f-4ca4-8cd2-1d9968a099a7"),
                            Title = "Cultural exchange"
                        },
                        new
                        {
                            DisciplineId = new Guid("2c21f43d-db2a-4108-bbae-0f325621d6ca"),
                            Title = "Vacation education"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("GradeNumber")
                        .HasMaxLength(15)
                        .HasColumnType("integer");

                    b.HasKey("GradeId");

                    b.HasIndex("GradeId")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = new Guid("d8ee03f8-fcd3-400d-b85b-8d35611e1039"),
                            GradeNumber = 1
                        },
                        new
                        {
                            GradeId = new Guid("6b9251fd-4755-42e2-9d9f-069865d3c46a"),
                            GradeNumber = 2
                        },
                        new
                        {
                            GradeId = new Guid("4b3ba0f2-5c49-4673-aacc-3b4bdfaae83f"),
                            GradeNumber = 3
                        },
                        new
                        {
                            GradeId = new Guid("dd9a4622-a941-42bd-a620-0a97a6e8fbde"),
                            GradeNumber = 4
                        },
                        new
                        {
                            GradeId = new Guid("25a69791-efa4-4dd8-9fc6-4ac62bc7d9bc"),
                            GradeNumber = 5
                        },
                        new
                        {
                            GradeId = new Guid("9bb6f03f-ec5e-40b1-b571-10f149d93202"),
                            GradeNumber = 6
                        },
                        new
                        {
                            GradeId = new Guid("d66ec862-99b5-4c91-a813-518e0ff67aaf"),
                            GradeNumber = 7
                        },
                        new
                        {
                            GradeId = new Guid("7a15b947-ed2c-4e51-ae88-0b4e1240a408"),
                            GradeNumber = 8
                        },
                        new
                        {
                            GradeId = new Guid("4d76eeb0-7575-403c-bdfa-071deab753d6"),
                            GradeNumber = 9
                        },
                        new
                        {
                            GradeId = new Guid("fa426f78-b675-42c3-933d-dec0484eba31"),
                            GradeNumber = 10
                        },
                        new
                        {
                            GradeId = new Guid("0dfd9a5b-fe0c-4a81-a101-795e063240b6"),
                            GradeNumber = 11
                        },
                        new
                        {
                            GradeId = new Guid("82c1c351-ce14-459c-83e9-497d191b858b"),
                            GradeNumber = 12
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("LanguageId");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("d9faf259-10e5-4bbd-ab93-6ac793581ca1"),
                            Title = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("810858c0-0054-4466-96e9-023bd7384314"),
                            Title = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("756a12f6-358a-4475-9637-3b97d3d1dfc3"),
                            Title = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("5e96614d-7ec5-4d16-a7db-04e8ead520df"),
                            Title = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("8c1421b6-95ba-4d12-930f-446de096a792"),
                            Title = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("2faf2fc2-de34-4a49-a19a-403d9a2344cb"),
                            Title = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("aee9ddf6-d322-4f32-a866-bf0defa6a2e4"),
                            Title = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("93a0c19f-64e0-4690-abf1-b5e15d7ee054"),
                            Title = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("93cdf397-3d7f-4c9b-af81-ae414e86ba99"),
                            Title = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("8a473aed-8be5-4d62-9ae6-69e1f289c2c9"),
                            Title = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("dc96b4cd-cfa4-40a3-9cf9-5cff25ecb029"),
                            Title = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("8d47cdcf-d4b9-4ddf-9eec-b582477abc26"),
                            Title = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("43d2cab6-546c-4253-b56c-12d5c9f82ece"),
                            Title = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("58956189-7d68-4c5d-954d-fdd4e9759bce"),
                            Title = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("47420a6b-68ae-4194-9dfc-6369498091d7"),
                            Title = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("1f75f468-5c7b-4f40-bcfe-d8f650bbda9c"),
                            Title = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("61be6d1c-3b0b-4c42-9446-6d92666f1277"),
                            Title = "Uzbek"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("CityId");

                    b.HasIndex("InstitutionId")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.InstitutionType", b =>
                {
                    b.Property<Guid>("InstitutionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("InstitutionTypeId");

                    b.HasIndex("InstitutionTypeId")
                        .IsUnique();

                    b.ToTable("InstitutionTypes");

                    b.HasData(
                        new
                        {
                            InstitutionTypeId = new Guid("9f14bf13-210e-47b1-81d4-b219bb26d88f"),
                            Title = "School"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("f994b448-fc2d-49b2-afbe-76f5079cf164"),
                            Title = "Gymnasium"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("091fe57a-2c1d-4002-8207-592da03bd55e"),
                            Title = "Lyceum"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("8665a819-e359-4501-96b1-679ed2c70d07"),
                            Title = "College"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("CityId");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassId")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("b347f5bd-c844-441e-8da1-ac0810b5d5fe"),
                            Title = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("2dbb48de-044d-40bd-b407-9f5afddb9c48"),
                            Title = "User"
                        },
                        new
                        {
                            RoleId = new Guid("830f6d1d-6268-4c60-8f75-1ca8965a8bee"),
                            Title = "Manager"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsATeacher")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAnExpert")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCreatedAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInstitutionVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("LastOnlineAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassDiscipline", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ClassId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("ClassDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId", "ClassId");

                    b.HasIndex("ClassId");

                    b.HasIndex("LanguageId", "ClassId")
                        .IsUnique();

                    b.ToTable("ClassLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.InstitutionTypeInstitution", b =>
                {
                    b.Property<Guid>("InstitutionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.HasKey("InstitutionTypeId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("InstitutionTypeId", "InstitutionId")
                        .IsUnique();

                    b.ToTable("InstitutionTypesInstitutions");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserDiscipline", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("UserDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserGrade", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GradeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId", "GradeId")
                        .IsUnique();

                    b.ToTable("UserGrades");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserLanguage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Feedback", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassReceiver")
                        .WithMany("ReceivedFeedBacks")
                        .HasForeignKey("ClassReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassSender")
                        .WithMany("SentFeedBacks")
                        .HasForeignKey("ClassSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Communication.Invitation", "Invitation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserRecipient")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("UserRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserSender")
                        .WithMany("SentFeedbacks")
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassReceiver");

                    b.Navigation("ClassSender");

                    b.Navigation("Invitation");

                    b.Navigation("UserRecipient");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassReceiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ClassReceiverId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassSender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("ClassSenderId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserReceiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("UserReceiverId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserSender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("UserSenderId")
                        .IsRequired();

                    b.Navigation("ClassReceiver");

                    b.Navigation("ClassSender");

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.City", null)
                        .WithMany("Establishments")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("Classes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiClass.Domain.Entities.Location.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiClass.Domain.Entities.Job.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassDiscipline", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "Class")
                        .WithMany("ClassDisciplines")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Education.Discipline", "Discipline")
                        .WithMany("ClassDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassLanguage", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "Class")
                        .WithMany("ClassLanguages")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Education.Language", "Language")
                        .WithMany("ClassLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.InstitutionTypeInstitution", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Job.Institution", "Institution")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Job.InstitutionType", "InstitutionType")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("InstitutionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("InstitutionType");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserDiscipline", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Discipline", "Discipline")
                        .WithMany("UserDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserDisciplines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserGrade", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Grade", "Grade")
                        .WithMany("UserGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserGrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserLanguage", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Language", "Language")
                        .WithMany("TeacherLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserRole", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Discipline", b =>
                {
                    b.Navigation("ClassDisciplines");

                    b.Navigation("UserDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Grade", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("UserGrades");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Language", b =>
                {
                    b.Navigation("ClassLanguages");

                    b.Navigation("TeacherLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.Navigation("InstitutionTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.InstitutionType", b =>
                {
                    b.Navigation("InstitutionTypes");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.Navigation("Establishments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.Navigation("ClassDisciplines");

                    b.Navigation("ClassLanguages");

                    b.Navigation("ReceivedFeedBacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentFeedBacks");

                    b.Navigation("SentInvitations");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ReceivedFeedbacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentFeedbacks");

                    b.Navigation("SentInvitations");

                    b.Navigation("UserDisciplines");

                    b.Navigation("UserGrades");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
