// <auto-generated />
using System;
using HiClass.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiClass.Persistence.Migrations
{
    [DbContext(typeof(SharedLessonDbContext))]
    partial class SharedLessonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<short?>("Rating")
                        .HasColumnType("SMALLINT");

                    b.Property<string>("ReasonForNotConducting")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserRecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasTheJointLesson")
                        .HasColumnType("boolean");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ClassReceiverId");

                    b.HasIndex("ClassSenderId");

                    b.HasIndex("FeedbackId")
                        .IsUnique();

                    b.HasIndex("InvitationId");

                    b.HasIndex("UserRecipientId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClassReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassSenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateOfInvitation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSenderId")
                        .HasColumnType("uuid");

                    b.HasKey("InvitationId");

                    b.HasIndex("ClassReceiverId");

                    b.HasIndex("ClassSenderId");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("UserReceiverId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Discipline", b =>
                {
                    b.Property<Guid>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("DisciplineId");

                    b.HasIndex("DisciplineId")
                        .IsUnique();

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DisciplineId = new Guid("8faaef47-1ccc-430e-82b7-c34e6fec0fd3"),
                            Title = "Russian language"
                        },
                        new
                        {
                            DisciplineId = new Guid("049aa87c-1452-4e52-8ec6-de63e9df5674"),
                            Title = "Russian literature"
                        },
                        new
                        {
                            DisciplineId = new Guid("374cff40-d16e-4841-ac75-a920594db078"),
                            Title = "English as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("ce09f719-e652-41a1-a9d7-760fb15ba699"),
                            Title = "German as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("10b7edc8-fcff-4282-a81d-e780b0c6d7e9"),
                            Title = "French as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("2ef60d0b-00ce-47f1-a482-67b5c1ac64fb"),
                            Title = "Italian as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("4daaaedd-102b-4a9d-a3ac-b2843c959662"),
                            Title = "Spanish as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("1c19033d-c496-4fec-8f82-500f6c0d109e"),
                            Title = "Chinese as a foreign language"
                        },
                        new
                        {
                            DisciplineId = new Guid("0469649d-b2b8-4485-b7b7-17edbdc0b265"),
                            Title = "Mathematics"
                        },
                        new
                        {
                            DisciplineId = new Guid("573c939a-dc69-4477-8a2d-9a7e66bf2893"),
                            Title = "Social science"
                        },
                        new
                        {
                            DisciplineId = new Guid("269af5c6-c372-47a0-ab74-920394d1c405"),
                            Title = "Physics"
                        },
                        new
                        {
                            DisciplineId = new Guid("79f29676-79a5-4aaa-9d57-3d1cc0d1886f"),
                            Title = "Astronomy"
                        },
                        new
                        {
                            DisciplineId = new Guid("ae32525a-ac6b-4ec6-b1e1-d441b007a087"),
                            Title = "Chemistry"
                        },
                        new
                        {
                            DisciplineId = new Guid("f945d8ec-43e0-47ae-976d-677b04878fc1"),
                            Title = "Biology"
                        },
                        new
                        {
                            DisciplineId = new Guid("a0c91bc4-ddf7-4060-a7ef-9c04d80ad2dc"),
                            Title = "Geography"
                        },
                        new
                        {
                            DisciplineId = new Guid("c53a4eb4-9133-4d58-9dea-a3a69d710db8"),
                            Title = "History"
                        },
                        new
                        {
                            DisciplineId = new Guid("7bd3bc0e-327a-4df7-9e58-06f975062c05"),
                            Title = "Computer science"
                        },
                        new
                        {
                            DisciplineId = new Guid("9e99b726-e402-4a20-b77d-9ba0def07053"),
                            Title = "Technology"
                        },
                        new
                        {
                            DisciplineId = new Guid("980c1be5-6c00-43c4-a259-edf1a8492fde"),
                            Title = "World art"
                        },
                        new
                        {
                            DisciplineId = new Guid("7f11d8c8-b0c7-4117-9652-250355489023"),
                            Title = "Fine arts"
                        },
                        new
                        {
                            DisciplineId = new Guid("675e1567-26f4-4436-80bc-bf61a65427a7"),
                            Title = "Crafts"
                        },
                        new
                        {
                            DisciplineId = new Guid("237d593f-74ef-464c-a25c-c4b840d0ec42"),
                            Title = "Natural science"
                        },
                        new
                        {
                            DisciplineId = new Guid("2978d56b-8e58-4b9b-8f69-1ebb00606830"),
                            Title = "Music"
                        },
                        new
                        {
                            DisciplineId = new Guid("9133f621-2d7b-4940-95bc-8f92d56b5791"),
                            Title = "Economics"
                        },
                        new
                        {
                            DisciplineId = new Guid("d7033842-ade3-4a5e-8edf-63d031972086"),
                            Title = "Regional studies"
                        },
                        new
                        {
                            DisciplineId = new Guid("f072b00c-1018-4c22-a24d-a8c191421ca8"),
                            Title = "Project-based learning"
                        },
                        new
                        {
                            DisciplineId = new Guid("a63257da-9d77-459b-a643-248c9f2670d8"),
                            Title = "Cultural exchange"
                        },
                        new
                        {
                            DisciplineId = new Guid("d56d0afd-edfb-4acd-8b01-761ff472fcb6"),
                            Title = "Vacation education"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("GradeNumber")
                        .HasMaxLength(15)
                        .HasColumnType("integer");

                    b.HasKey("GradeId");

                    b.HasIndex("GradeId")
                        .IsUnique();

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = new Guid("79399de2-592f-4795-813c-997dbe014804"),
                            GradeNumber = 1
                        },
                        new
                        {
                            GradeId = new Guid("336fe364-887d-432d-a9bf-26d9a07d6ede"),
                            GradeNumber = 2
                        },
                        new
                        {
                            GradeId = new Guid("0239ba79-3909-4372-aa1c-37cc78d5d1ae"),
                            GradeNumber = 3
                        },
                        new
                        {
                            GradeId = new Guid("810d8b44-bf6e-49eb-94e4-efcd9cf76b43"),
                            GradeNumber = 4
                        },
                        new
                        {
                            GradeId = new Guid("96152dfe-00df-489e-b642-e4d710bb7e8c"),
                            GradeNumber = 5
                        },
                        new
                        {
                            GradeId = new Guid("16f82141-5650-4550-8dc7-fda8bae3d302"),
                            GradeNumber = 6
                        },
                        new
                        {
                            GradeId = new Guid("dc97f724-18db-4c8f-b480-6ddec9195a05"),
                            GradeNumber = 7
                        },
                        new
                        {
                            GradeId = new Guid("1580cb85-f107-4c4a-b80b-93607a79b0ae"),
                            GradeNumber = 8
                        },
                        new
                        {
                            GradeId = new Guid("81a35f8e-b646-447c-b64b-09a231c9885d"),
                            GradeNumber = 9
                        },
                        new
                        {
                            GradeId = new Guid("a71f921e-d88a-4e1e-b9e3-ed17b1629f34"),
                            GradeNumber = 10
                        },
                        new
                        {
                            GradeId = new Guid("072b2ae9-7013-42d7-aa3f-ac403f3a820d"),
                            GradeNumber = 11
                        },
                        new
                        {
                            GradeId = new Guid("2c962c58-2ce4-47cc-92a3-c693709f8c13"),
                            GradeNumber = 12
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("LanguageId");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = new Guid("69a762ae-c339-4da7-b60d-9e8b810d359b"),
                            Title = "Russian"
                        },
                        new
                        {
                            LanguageId = new Guid("e39fbadf-4f96-4b18-bba1-fbc9ddf24bd4"),
                            Title = "English"
                        },
                        new
                        {
                            LanguageId = new Guid("683c2ac8-d628-4d05-ab23-ec67bcc24e0a"),
                            Title = "German"
                        },
                        new
                        {
                            LanguageId = new Guid("b5e689e6-0cdd-4608-9570-40aa1771a1d5"),
                            Title = "Italian"
                        },
                        new
                        {
                            LanguageId = new Guid("6433fee4-3724-4e82-81e1-866f4a1c7bf0"),
                            Title = "Spanish"
                        },
                        new
                        {
                            LanguageId = new Guid("3b94bbcb-696f-4b84-af6c-543615cd0ee3"),
                            Title = "French"
                        },
                        new
                        {
                            LanguageId = new Guid("44026d80-40cf-4f2a-9170-5940631f1eb1"),
                            Title = "Hungarian"
                        },
                        new
                        {
                            LanguageId = new Guid("351ad011-ec9f-4189-ae17-dc06d29ce135"),
                            Title = "Portuguese"
                        },
                        new
                        {
                            LanguageId = new Guid("b5fafb37-4c29-4cc6-8a86-3eb9d4a194de"),
                            Title = "Belarusian"
                        },
                        new
                        {
                            LanguageId = new Guid("de916d64-f59b-47c8-ba62-75ed5dcb85f5"),
                            Title = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = new Guid("6038b6d1-dbde-4733-98b7-a4f9430cef9c"),
                            Title = "Armenian"
                        },
                        new
                        {
                            LanguageId = new Guid("6bf4944a-d021-467f-9916-9063ac1fec3e"),
                            Title = "Georgian"
                        },
                        new
                        {
                            LanguageId = new Guid("fdabd86a-f29e-4960-87ab-cfb1cfc1c6ad"),
                            Title = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = new Guid("1a71babf-e79c-4fcd-a3a2-bb1372d2d6cd"),
                            Title = "Kazakh"
                        },
                        new
                        {
                            LanguageId = new Guid("2fdf7b20-1999-439a-bbbe-6721aab91325"),
                            Title = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = new Guid("98525cb0-b4d0-4a93-a8e8-40e2ae98972e"),
                            Title = "Tajik"
                        },
                        new
                        {
                            LanguageId = new Guid("55fccec2-909f-4464-bac5-9775c967cb17"),
                            Title = "Uzbek"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("CityId");

                    b.HasIndex("InstitutionId")
                        .IsUnique();

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.InstitutionType", b =>
                {
                    b.Property<Guid>("InstitutionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("InstitutionTypeId");

                    b.HasIndex("InstitutionTypeId")
                        .IsUnique();

                    b.ToTable("InstitutionTypes");

                    b.HasData(
                        new
                        {
                            InstitutionTypeId = new Guid("6f48fbe2-e7cb-4493-bdea-8d7e3289a226"),
                            Title = "School"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("2fb7ac4d-851b-44cf-ac44-dc708f4635b8"),
                            Title = "Gymnasium"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("83d75271-6c4b-4095-9fef-e931a88f1d3f"),
                            Title = "Lyceum"
                        },
                        new
                        {
                            InstitutionTypeId = new Guid("526981f8-2b85-4d40-a5c0-1090f1a4d313"),
                            Title = "College"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("CityId");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassId")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("fff170a9-98dc-42fc-86a0-f1a2cf287776"),
                            Title = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("b3c9a0eb-e428-4f7f-b210-8f4b1c40b309"),
                            Title = "User"
                        },
                        new
                        {
                            RoleId = new Guid("b368396e-b258-4ec8-acc8-3c2fdd59beba"),
                            Title = "Manager"
                        });
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsATeacher")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAnExpert")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCreatedAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInstitutionVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("LastOnlineAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassDiscipline", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("ClassId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("ClassDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassLanguage", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.HasKey("LanguageId", "ClassId");

                    b.HasIndex("ClassId");

                    b.HasIndex("LanguageId", "ClassId")
                        .IsUnique();

                    b.ToTable("ClassLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.InstitutionTypeInstitution", b =>
                {
                    b.Property<Guid>("InstitutionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.HasKey("InstitutionTypeId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("InstitutionTypeId", "InstitutionId")
                        .IsUnique();

                    b.ToTable("InstitutionTypesInstitutions");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserDiscipline", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("UserId", "DisciplineId")
                        .IsUnique();

                    b.ToTable("UserDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserGrade", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "GradeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId", "GradeId")
                        .IsUnique();

                    b.ToTable("UserGrades");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserLanguage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Feedback", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassReceiver")
                        .WithMany("ReceivedFeedBacks")
                        .HasForeignKey("ClassReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassSender")
                        .WithMany("SentFeedBacks")
                        .HasForeignKey("ClassSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Communication.Invitation", "Invitation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserRecipient")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("UserRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserSender")
                        .WithMany("SentFeedbacks")
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassReceiver");

                    b.Navigation("ClassSender");

                    b.Navigation("Invitation");

                    b.Navigation("UserRecipient");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassReceiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ClassReceiverId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.Class", "ClassSender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("ClassSenderId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserReceiver")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("UserReceiverId")
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "UserSender")
                        .WithMany("SentInvitations")
                        .HasForeignKey("UserSenderId")
                        .IsRequired();

                    b.Navigation("ClassReceiver");

                    b.Navigation("ClassSender");

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.City", null)
                        .WithMany("Establishments")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("Classes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Location.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiClass.Domain.Entities.Location.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HiClass.Domain.Entities.Job.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassDiscipline", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "Class")
                        .WithMany("ClassDisciplines")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Education.Discipline", "Discipline")
                        .WithMany("ClassDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.ClassLanguage", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Class", "Class")
                        .WithMany("ClassLanguages")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Education.Language", "Language")
                        .WithMany("ClassLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.InstitutionTypeInstitution", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Job.Institution", "Institution")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Job.InstitutionType", "InstitutionType")
                        .WithMany("InstitutionTypes")
                        .HasForeignKey("InstitutionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("InstitutionType");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserDiscipline", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Discipline", "Discipline")
                        .WithMany("UserDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserDisciplines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserGrade", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Grade", "Grade")
                        .WithMany("UserGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserGrades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserLanguage", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Education.Language", "Language")
                        .WithMany("TeacherLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.EntityConnections.UserRole", b =>
                {
                    b.HasOne("HiClass.Domain.Entities.Main.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HiClass.Domain.Entities.Main.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Communication.Invitation", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Discipline", b =>
                {
                    b.Navigation("ClassDisciplines");

                    b.Navigation("UserDisciplines");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Grade", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("UserGrades");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Education.Language", b =>
                {
                    b.Navigation("ClassLanguages");

                    b.Navigation("TeacherLanguages");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.Institution", b =>
                {
                    b.Navigation("InstitutionTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Job.InstitutionType", b =>
                {
                    b.Navigation("InstitutionTypes");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.City", b =>
                {
                    b.Navigation("Establishments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Location.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Class", b =>
                {
                    b.Navigation("ClassDisciplines");

                    b.Navigation("ClassLanguages");

                    b.Navigation("ReceivedFeedBacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentFeedBacks");

                    b.Navigation("SentInvitations");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HiClass.Domain.Entities.Main.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ReceivedFeedbacks");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentFeedbacks");

                    b.Navigation("SentInvitations");

                    b.Navigation("UserDisciplines");

                    b.Navigation("UserGrades");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
